/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': '#DE6F14',
        'primary-light': 'var(--color-primary-light)',
        'primary-white': 'var(--color-primary-white)',
        success: 'var(--color-success)',
        error: 'var(--color-error)',
        warning: 'var(--color-warning)',
        'blue-primary': 'var(--color-blue-primary)',
        'blue-light': 'var(--color-blue-light)',
        'blue-pale': 'var(--color-blue-pale)',
        purple: 'var(--color-purple)',
        indigo: 'var(--color-indigo)',
        sky: 'var(--color-sky)',
        teal: 'var(--color-teal)',
        green: 'var(--color-green)',
        yellow: 'var(--color-yellow)',
        orange: 'var(--color-orange)',
        red: 'var(--color-red)',
        'bg-100': 'var(--color-bg-100)',
        'bg-200': 'var(--color-bg-200)',
        'bg-300': 'var(--color-bg-300)',
        'bg-400': 'var(--color-bg-400)',
        'dark-80': 'var(--color-dark-80)',
        'dark-40': 'var(--color-dark-40)',
        'dark-20': 'var(--color-dark-20)',
        'dark-10': 'var(--color-dark-10)',
        'dark-04': 'var(--color-dark-04)',
        'white-80': 'var(--color-white-80)',
        'white-40': 'var(--color-white-40)',
        'white-20': 'var(--color-white-20)',
        'white-15': 'var(--color-white-15)',
        'white-10': 'var(--color-white-10)',
        'white-04': 'var(--color-white-04)',
      },
      borderRadius: {
        card: 'var(--border-radius-card)',
        item: 'var(--border-radius-item)',
        button: 'var(--border-radius-button)',
        tag: 'var(--border-radius-tag)',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        heading: ['var(--font-size-heading)', 'var(--line-height-heading)'],
        body: ['var(--font-size-body)', 'var(--line-height-body)'],
        caption: ['var(--font-size-caption)', 'var(--line-height-caption)'],
        button: ['var(--font-size-button)', 'var(--line-height-button)'],
        small: ['var(--font-size-small)', 'var(--line-height-small)'],
      },
      spacing: {
        card: 'var(--padding-card)',
        item: 'var(--padding-item)',
        button: 'var(--padding-button)',
        default: 'var(--gap-default)',
        tight: 'var(--gap-tight)',
        xs: 'var(--gap-xs)',
      },
    },
  },
  plugins: [],
};
